spring:
  redis:
    database: 1
    host: 127.0.0.1
    port: 6379
    password:
    timeout: 500
    jedis:
      pool:
        # 连接池最大连接数（使用负值表示没有限制）
        max-active: 100
        # 连接池最大阻塞等待时间（使用负值表示没有限制）
        max-wait: 100
        # 连接池中的最大空闲连接
        max-idle: 50
        min-idle: 20